# Generated by Django 3.0.6 on 2020-05-13 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'managed': True},
        ),
    ]
