# Generated by Django 3.0.6 on 2020-05-13 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20200513_0512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='created_by',
        ),
    ]
