# Generated by Django 3.0.6 on 2020-05-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_remove_state_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='created_by',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
