# Generated by Django 3.0.6 on 2020-05-19 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0004_state_created_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.AlterModelOptions(
            name='addressalias',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='addressaliastypeaut',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='addressdefaultgeocode',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='addressdetail',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='addressmeshblock2011',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='addressmeshblock2016',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='addresssite',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='addresssitegeocode',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='addresstypeaut',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='djangomigrations',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='flattypeaut',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='geocodedleveltypeaut',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='geocodereliabilityaut',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='geocodetypeaut',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='leveltypeaut',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='locality',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='localityalias',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='localityaliastypeaut',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='localityclassaut',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='localityneighbour',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='localitypoint',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='mb2011',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='mb2016',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='mbmatchcodeaut',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='primarysecondary',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='psjointypeaut',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='streetclassaut',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='streetlocality',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='streetlocalityalias',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='streetlocalityaliastypeaut',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='streetlocalitypoint',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='streetsuffixaut',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='streettypeaut',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='state',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
