# Generated by Django 3.0.6 on 2020-05-19 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_auto_20200519_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locality',
            name='gnaf_reliability_code',
            field=models.ForeignKey(db_column='gnaf_reliability_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='geocodereliabilityaut', to='places.GeocodeReliabilityAut'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='locality_class_code',
            field=models.ForeignKey(db_column='locality_class_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='localityclassaut', to='places.LocalityClassAut'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='state_pid',
            field=models.ForeignKey(db_column='state_pid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='state', to='places.State'),
        ),
    ]
