# Generated by Django 3.0.6 on 2020-05-20 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_auto_20200519_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='created_by',
        ),
    ]
