# Generated by Django 3.0.6 on 2020-06-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_remove_state_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_detail_pid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('date_last_modified', models.DateField(blank=True, null=True)),
                ('date_retired', models.DateField(blank=True, null=True)),
                ('building_name', models.CharField(blank=True, max_length=200, null=True)),
                ('lot_number_prefix', models.CharField(blank=True, max_length=2, null=True)),
                ('lot_number', models.CharField(blank=True, max_length=5, null=True)),
                ('lot_number_suffix', models.CharField(blank=True, max_length=2, null=True)),
                ('lot_number_combined', models.TextField(blank=True, null=True)),
                ('flat_type_code', models.CharField(blank=True, max_length=7, null=True)),
                ('flat_number_prefix', models.CharField(blank=True, max_length=2, null=True)),
                ('flat_number', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('flat_number_suffix', models.CharField(blank=True, max_length=2, null=True)),
                ('flat_number_combined', models.TextField(blank=True, null=True)),
                ('level_type_code', models.CharField(blank=True, max_length=4, null=True)),
                ('level_number_prefix', models.CharField(blank=True, max_length=2, null=True)),
                ('level_number', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('level_number_suffix', models.CharField(blank=True, max_length=2, null=True)),
                ('level_number_combined', models.TextField(blank=True, null=True)),
                ('number_first_prefix', models.CharField(blank=True, max_length=3, null=True)),
                ('number_first', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('number_first_suffix', models.CharField(blank=True, max_length=2, null=True)),
                ('number_first_combined', models.TextField(blank=True, null=True)),
                ('number_last_prefix', models.CharField(blank=True, max_length=3, null=True)),
                ('number_last', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('number_last_suffix', models.CharField(blank=True, max_length=2, null=True)),
                ('number_last_combined', models.TextField(blank=True, null=True)),
                ('house_number', models.TextField(blank=True, null=True)),
                ('street_locality_pid', models.CharField(blank=True, max_length=15, null=True)),
                ('street_name', models.CharField(blank=True, max_length=100, null=True)),
                ('street_type', models.CharField(blank=True, max_length=50, null=True)),
                ('street_suffix_code', models.CharField(blank=True, max_length=15, null=True)),
                ('street_suffix_name', models.CharField(blank=True, max_length=50, null=True)),
                ('street', models.TextField(blank=True, null=True)),
                ('locality_pid', models.CharField(blank=True, max_length=15, null=True)),
                ('locality_name', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=3, null=True)),
                ('alias_principal', models.CharField(blank=True, max_length=1, null=True)),
                ('postcode', models.CharField(blank=True, max_length=4, null=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True)),
                ('address_site_pid', models.CharField(blank=True, max_length=15, null=True)),
                ('address_type_name', models.CharField(blank=True, max_length=50, null=True)),
                ('address_site_name', models.CharField(blank=True, max_length=200, null=True)),
                ('level_geocoded_code', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('primary_secondary', models.CharField(blank=True, max_length=1, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
            ],
            options={
                'db_table': 'address',
                'managed': True,
            },
        ),
    ]
